In [11]:
import pandas as pd

# 读取数据
data_raw = pd.read_excel('data_without_dopants.xlsx')
data_raw.head()

,Index,Cathode,O,N,SSA,Smicro,Smeso,PV,Vmicro,Vmeso,...,ID/IG,Electrolyte,M,Anion,CC,AML,PW,CD,Cs,Ref
0,1,N-3D-PCN,7.15,3.52,1546.1,NaN,NaN,0.5753,0.5407,0.03714,...,1.029,2M ZnSO4,2,SO4,carbon cloth,1.0,1.6,0.10,85.0,10.1016/j.jallcom.2023.172407.
1,2,NPC,21.55,3.29,1140.8,341.3,NaN,0.8600,0.1800,NaN,...,0.820,1M Zn(CF3SO3)2,1,OTf,stainless-steel mesh,2.5,1.8,0.10,90.2,10.1016/j.jallcom.2022.164536
2,3,NPC,21.55,3.29,1140.8,341.3,NaN,0.8600,0.1800,NaN,...,0.820,1M Zn(CF3SO3)2,1,OTf,stainless-steel mesh,2.5,1.8,0.25,86.3,NaN
3,4,NPC,21.55,3.29,1140.8,341.3,NaN,0.8600,0.1800,NaN,...,0.820,1M Zn(CF3SO3)2,1,OTf,stainless-steel mesh,2.5,1.8,0.50,79.9,NaN
4,5,NPC,21.55,3.29,1140.8,341.3,NaN,0.8600,0.1800,NaN,...,0.820,1M Zn(CF3SO3)2,1,OTf,stainless-steel mesh,2.5,1.8,1.00,70.3,NaN

In [12]:
# 列清理
data = data_raw.drop(["Index", "Cathode", "Smicro", "Smeso", "Vmicro", "Vmeso", "Electrolyte", "Ref"], axis=1)
data

,O,N,SSA,PV,RMIC,Dap,ID/IG,M,Anion,CC,AML,PW,CD,Cs
0,7.15,3.52,1546.1,0.5753,93.985747,1.488390,1.029,2,SO4,carbon cloth,1.0,1.6,0.10,85.0
1,21.55,3.29,1140.8,0.8600,20.930233,3.015428,0.820,1,OTf,stainless-steel mesh,2.5,1.8,0.10,90.2
2,21.55,3.29,1140.8,0.8600,20.930233,3.015428,0.820,1,OTf,stainless-steel mesh,2.5,1.8,0.25,86.3
3,21.55,3.29,1140.8,0.8600,20.930233,3.015428,0.820,1,OTf,stainless-steel mesh,2.5,1.8,0.50,79.9
4,21.55,3.29,1140.8,0.8600,20.930233,3.015428,0.820,1,OTf,stainless-steel mesh,2.5,1.8,1.00,70.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,11.38,8.71,499.8,0.5043,20.488195,4.040000,1.070,2,SO4,stainless-steel mesh,3.0,1.6,1.00,90.1
596,11.38,8.71,499.8,0.5043,20.488195,4.040000,1.070,2,SO4,stainless-steel mesh,3.0,1.6,2.00,84.7
597,11.38,8.71,499.8,0.5043,20.488195,4.040000,1.070,2,SO4,stainless-steel mesh,3.0,1.6,5.00,75.5
598,11.38,8.71,499.8,0.5043,20.488195,4.040000,1.070,2,SO4,stainless-steel mesh,3.0,1.6,8.00,69.4
599,11.38,8.71,499.8,0.5043,20.488195,4.040000,1.070,2,SO4,stainless-steel mesh,3.0,1.6,10.00,66.4

In [13]:
# 数据分布统计
statistics = data.describe(include='all')
statistics

,O,N,SSA,PV,RMIC,Dap,ID/IG,M,Anion,CC,AML,PW,CD,Cs
count,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600.000000,600,600,542.000000,600.000000,600.000000,600.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,7,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SO4,stainless-steel mesh,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,453,432,NaN,NaN,NaN,NaN
mean,8.537917,3.229583,1752.506000,1.252717,45.155167,3.042198,1.261386,1.680000,NaN,NaN,2.224649,1.641200,10.791250,93.532957
std,4.267782,2.946442,916.673178,0.725015,25.864385,1.616053,0.605709,0.654457,NaN,NaN,3.120758,0.083689,22.160702,39.907359
min,1.900000,0.000000,225.220000,0.100000,0.000000,1.488390,0.700000,1.000000,NaN,NaN,1.000000,1.600000,0.050000,14.700000
25%,5.640000,1.300000,972.400000,0.721000,20.930233,1.980000,0.950000,1.000000,NaN,NaN,1.000000,1.600000,0.500000,66.800000
50%,7.600000,2.570000,1655.000000,1.070000,49.093264,2.335766,1.044000,2.000000,NaN,NaN,1.500000,1.600000,3.000000,89.416667
75%,10.580000,4.200000,2370.000000,1.740000,67.000000,3.637909,1.110000,2.000000,NaN,NaN,2.000000,1.600000,10.000000,115.335000
max,21.550000,13.570000,3553.100000,3.428000,95.446286,9.342348,3.500000,3.000000,NaN,NaN,45.000000,2.000000,200.000000,268.000000

In [14]:
# 填充缺失值
data["AML"] = data["AML"].fillna(data["AML"].median())

# 将Anion列的数据转换为数值
data["Anion"] = data["Anion"].map({"SO4": 1, "OTf": 0})

# 将CC列删除
data=data.drop(["CC"], axis=1)

data

,O,N,SSA,PV,RMIC,Dap,ID/IG,M,Anion,AML,PW,CD,Cs
0,7.15,3.52,1546.1,0.5753,93.985747,1.488390,1.029,2,1,1.0,1.6,0.10,85.0
1,21.55,3.29,1140.8,0.8600,20.930233,3.015428,0.820,1,0,2.5,1.8,0.10,90.2
2,21.55,3.29,1140.8,0.8600,20.930233,3.015428,0.820,1,0,2.5,1.8,0.25,86.3
3,21.55,3.29,1140.8,0.8600,20.930233,3.015428,0.820,1,0,2.5,1.8,0.50,79.9
4,21.55,3.29,1140.8,0.8600,20.930233,3.015428,0.820,1,0,2.5,1.8,1.00,70.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,11.38,8.71,499.8,0.5043,20.488195,4.040000,1.070,2,1,3.0,1.6,1.00,90.1
596,11.38,8.71,499.8,0.5043,20.488195,4.040000,1.070,2,1,3.0,1.6,2.00,84.7
597,11.38,8.71,499.8,0.5043,20.488195,4.040000,1.070,2,1,3.0,1.6,5.00,75.5
598,11.38,8.71,499.8,0.5043,20.488195,4.040000,1.070,2,1,3.0,1.6,8.00,69.4
599,11.38,8.71,499.8,0.5043,20.488195,4.040000,1.070,2,1,3.0,1.6,10.00,66.4

In [15]:
# 保存一份数据
data.to_csv('dataset.csv', index=False)